require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - '.git/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - RSpec.describe
    - describe

RSpec/FilePath:
  CustomTransform:
    CarrierWave: carrierwave

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false
